[workspace]
resolver = "3"
members = ["game", "engine"]

[workspace.dependencies]
engine = { path = "../engine" }
bevy = { version = "0.17.3", features = ["bevy_dev_tools"] }
rand_core = "0.9"
bevy_rand = "0.12"
bevy_prng = { version = "0.12", features = ["rand_chacha", "wyrand"] }
tracing = "0.1.44"
tracing-tree = "0.4.1"
tracing-subscriber = { version = "0.3.22", features = ["json"] }
pretty_assertions = "1.4.1"
